// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ30wY_RjsUlmbE6hxI0Q_egrM_pFrJ9o',
    appId: '1:30663326675:web:9ead55fc92541aa7434d26',
    messagingSenderId: '30663326675',
    projectId: 'bitirme-tezi-8ad8f',
    authDomain: 'bitirme-tezi-8ad8f.firebaseapp.com',
    storageBucket: 'bitirme-tezi-8ad8f.appspot.com',
    measurementId: 'G-5RYWHD8HRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd3EKbZ1NyAuv7XIpQQ80lmp8FPrO7W7Q',
    appId: '1:30663326675:android:296308cd53dfea71434d26',
    messagingSenderId: '30663326675',
    projectId: 'bitirme-tezi-8ad8f',
    storageBucket: 'bitirme-tezi-8ad8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgVnyCs10byvYfu-KbhrkOW581M8U6bbg',
    appId: '1:30663326675:ios:34d9bdbea05be947434d26',
    messagingSenderId: '30663326675',
    projectId: 'bitirme-tezi-8ad8f',
    storageBucket: 'bitirme-tezi-8ad8f.appspot.com',
    iosBundleId: 'com.example.bitirmeTezi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgVnyCs10byvYfu-KbhrkOW581M8U6bbg',
    appId: '1:30663326675:ios:38a6e1381e50de72434d26',
    messagingSenderId: '30663326675',
    projectId: 'bitirme-tezi-8ad8f',
    storageBucket: 'bitirme-tezi-8ad8f.appspot.com',
    iosBundleId: 'com.example.bitirmeTezi.RunnerTests',
  );
}
